project:
  type: website
  output-dir: docs

website:
  title: "SPS 506"
  site-url: "https://sps506.classes.chrisbirdsall.com"
  navbar: false
  search: false

format:
  html:
    theme:
      - cosmo
      - styles.scss
    css: styles.css
    toc: false
    anchor-sections: false

editor: visual
